### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [IOINITID/degreezzy#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by IOINITID** [comment]
Yes, I was thinking of typing functions. If you can, please make a Pull Request, I will be glad.

**Comment by geopic** [comment]
Great, I'll start on it tomorrow 👍

**Comment by IOINITID** [comment]
Thanks!😺
